name: LintGoCode

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.x'

      - run: go mod download
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip: '!**/.git'
        


